#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12
TOTAL_MINUTES=48

PRIVACY_URL="https://vnnkl.github.io/tvos-bitcoin-chart/privacy/"
SUPPORT_URL="https://vnnkl.github.io/tvos-bitcoin-chart/"
BUNDLE_ID="com.bitcointerminal.BitcoinTerminal"
COPY_FILE="/tmp/bitcoin-terminal-appstore-copy.txt"

banner "Bitcoin Terminal — App Store release"

# ── 1 · Commit & push release prep ─────────────────────────────────────────
stage "Commit & push release prep" 3
say "The repo has release changes (brand assets, privacy policy, Info.plist)."
say "They must be on GitHub before Pages can serve the privacy policy."
printf '\n'
git status --short | head -30 || true
printf '\n'
if confirm "Commit everything above and push to origin?"; then
  git add -A
  git commit -m "chore: App Store release prep (brand assets, privacy policy, plist)" || note "nothing to commit"
  git push origin HEAD || warn "push failed — push manually before stage 2"
else
  SKIPPED+=("commit & push release prep — do it before enabling Pages")
  warn "skipped — remember to push before stage 2"
fi

# ── 2 · GitHub Pages ────────────────────────────────────────────────────────
stage "Enable GitHub Pages" 4
say "Apple requires a public privacy-policy URL. We'll serve docs/ via Pages."
open_url "https://github.com/vnnkl/tvos-bitcoin-chart/settings/pages"
step "Under 'Build and deployment' → Source: choose 'Deploy from a branch'."
step "Branch: your default branch (main) · Folder: /docs · Save."
note "First deploy takes a minute or two. Check the Actions tab for 'pages build'."
pause "Press Enter once Pages shows the site is live..."
open_url "$PRIVACY_URL"
step "Confirm the privacy policy renders at the URL just opened."
pause
write_env PRIVACY_POLICY_URL "$PRIVACY_URL"
write_env SUPPORT_URL "$SUPPORT_URL"

# ── 3 · Apple Developer membership ─────────────────────────────────────────
stage "Apple Developer Program membership" 2
say "Distribution requires an active paid membership (\$99/year) for team YQ4EC2TEL3."
open_url "https://developer.apple.com/account"
step "Sign in and check the Membership card shows 'Apple Developer Program' as Active."
warn "If it shows 'Apple Developer' (free tier) you must enroll before continuing."
pause "Membership is active?"

# ── 4 · Xcode account sign-in ───────────────────────────────────────────────
stage "Sign in to Xcode" 2
say "Automatic signing needs your Apple ID inside Xcode."
step "Xcode → Settings… → Accounts → '+' → add the Apple ID for team YQ4EC2TEL3."
step "Confirm the team is listed under that account."
note "Certificates get created automatically during the first archive — nothing else to do here."
pause "Signed in?"

# ── 5 · Register the App ID ─────────────────────────────────────────────────
stage "Register the bundle identifier" 3
say "App Store Connect can only create an app for a registered App ID."
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Click '+' → App IDs → App → Continue."
step "Description: Bitcoin Terminal"
step "Bundle ID: Explicit → ${BUNDLE_ID}"
step "Leave all capabilities unchecked → Continue → Register."
pause "App ID registered?"

# ── 6 · Create the App Store Connect record ────────────────────────────────
stage "Create the app in App Store Connect" 4
open_url "https://appstoreconnect.apple.com/apps"
step "Click '+' → New App."
step "Platform: tvOS · Bundle ID: ${BUNDLE_ID}"
step "Name: 'Bitcoin Terminal' — if taken, try 'Bitcoin Terminal TV' or similar."
step "Primary language: English (U.S.) · SKU: anything unique, e.g. bitcoin-terminal-tvos"
step "User access: Full Access → Create."
ask APP_NAME "App name you ended up with [Bitcoin Terminal]:"
[[ -z "${APP_NAME}" ]] && APP_NAME="Bitcoin Terminal"
ask ASC_SKU "SKU you entered [bitcoin-terminal-tvos]:"
[[ -z "${ASC_SKU}" ]] && ASC_SKU="bitcoin-terminal-tvos"
write_env APP_NAME "$APP_NAME"
write_env ASC_SKU "$ASC_SKU"

# ── 7 · Archive & upload ────────────────────────────────────────────────────
stage "Archive and upload the build" 10
say "Now the actual binary. Opening the Xcode project…"
open BitcoinTerminal.xcodeproj 2>/dev/null || warn "open the project manually in Xcode"
step "Scheme: BitcoinTerminal · Destination: 'Any tvOS Device (arm64)'."
step "Menu: Product → Archive (takes a few minutes)."
step "In the Organizer window that opens: Distribute App → App Store Connect → Upload."
step "Accept the defaults (auto-signing, upload symbols) and finish."
note "First run may prompt to create an Apple Distribution certificate — allow it."
note "Export compliance is already answered in the Info.plist (uses only exempt HTTPS)."
pause "Upload finished?"

# ── 8 · App Privacy & age rating ───────────────────────────────────────────
stage "App Privacy & age rating" 4
open_url "https://appstoreconnect.apple.com/apps"
step "Open your app → App Privacy → Get Started."
step "Privacy policy URL: ${PRIVACY_URL}"
step "Data collection: 'Data Not Collected' → Publish."
step "Then: App Store tab → Age Rating → answer the questionnaire — all 'None'."
note "A price ticker has no gambling/violence/web-browsing content; expect a 4+ rating."
pause "Privacy and age rating done?"

# ── 9 · Metadata & screenshots ─────────────────────────────────────────────
stage "Store listing: text & screenshots" 8
cat > "$COPY_FILE" <<'COPY_EOF'
── Description ──────────────────────────────────────────────
Bitcoin Terminal turns your Apple TV into a full-screen market monitor.

Watch live Bitcoin candlestick charts rendered terminal-style, with a
real-time order book ladder, live trade feed, and volume profile — all
streaming directly from public market data, updating tick by tick.

FEATURES
• Live candlestick chart with selectable timeframes (1m to 1w)
• Session high/low markers and a live price indicator
• Real-time order book depth ladder
• Streaming trade tape
• STRC dashboard tracking public SEC filing data
• Terminal aesthetic built for the living room — no menus in your way

Bitcoin Terminal displays public market data for informational purposes
only. It is not financial advice. No account, no sign-up, no tracking.

── Keywords (≤100 chars) ────────────────────────────────────
bitcoin,btc,crypto,chart,candlestick,price,ticker,order book,market,trading,terminal

── Promotional text ─────────────────────────────────────────
Your living-room Bitcoin terminal: live charts, order book, and trades on
the big screen.

── Review notes ─────────────────────────────────────────────
All market data shown is public: Bitcoin prices via Binance public REST
and WebSocket APIs (api.binance.com / stream.binance.com), and public SEC
filing data for the STRC ticker via strc.live. The app is display-only:
no accounts, no login, no trading, no purchases, and no data collection.
A "not financial advice" disclaimer is included.
COPY_EOF
say "Copy-paste-ready listing text written to:"
note "  $COPY_FILE"
open "$COPY_FILE" 2>/dev/null || true
open docs/screenshots 2>/dev/null || true
step "In your app's App Store tab → 1.0 Prepare for Submission:"
step "Paste the description, keywords, and promotional text from the copy file."
step "Support URL: ${SUPPORT_URL}"
step "Upload the three 1920×1080 screenshots from docs/screenshots (chart, STRC, settings)."
note "You can add up to 10 screenshots; 3 is enough to submit."
step "Copyright: © 2026 Bitcoin Terminal."
pause "Listing filled in?"

# ── 10 · Pricing ────────────────────────────────────────────────────────────
stage "Pricing & availability" 2
step "In your app: Pricing and Availability → Price: 0 (Free)."
step "Availability: all countries/regions (default) → Save."
pause "Pricing saved?"

# ── 11 · TestFlight sanity check (optional) ────────────────────────────────
stage "TestFlight sanity check (optional)" 3
say "Once the uploaded build finishes processing (5–30 min) it appears under TestFlight."
step "Optional but recommended: install the TestFlight app on your Apple TV,"
step "add yourself as an internal tester, and run the build on real hardware."
note "You can skip this and submit directly — the build just needs to finish processing."
pause "Ready to move on?"

# ── 12 · Submit for review ──────────────────────────────────────────────────
stage "Submit for review" 3
step "App Store tab → 1.0 Prepare for Submission → Build section → select your uploaded build."
step "Paste the review notes from $COPY_FILE into 'Notes' under App Review Information."
step "Add your contact info in App Review Information."
if confirm "Everything filled in — submit the app for review now?"; then
  step "Click 'Add for Review' → 'Submit to App Review'."
  say "Review typically takes 1–3 days. You'll get an email either way. 🚀"
else
  SKIPPED+=("final submission — submit from App Store Connect when ready")
fi
pause "Done?"

finish
